title: Trying GitHub Pages
author: Sanket Patel
email: sanketpatel.301090@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Trying GitHub Pages. Courtesy of GitHub courses

# social links
twitter_username: sunk_8
github_username:  sanketjpatel

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
